create table if not exists public.favourites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  gif_id text not null,
  gif_data jsonb not null,
  created_at timestamptz not null default now(),
  unique (user_id, gif_id)
);

create table if not exists public.profiles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  display_name text,
  avatar_url text,
  accent text,
  landing_page text,
  helper_mode boolean default false,
  offline_cache boolean default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.collections (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null,
  description text,
  color text,
  is_public boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.collection_items (
  id bigint generated by default as identity primary key,
  collection_id uuid not null references public.collections (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  gif_id text not null,
  position integer not null default 0,
  unique (collection_id, gif_id)
);

create table if not exists public.gif_metadata (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  gif_id text not null,
  notes text default '',
  tags text[] default '{}',
  use_later boolean not null default false,
  imported boolean not null default false,
  custom_source_url text,
  updated_at timestamptz not null default now(),
  unique (user_id, gif_id)
);

create table if not exists public.view_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  gif_id text not null,
  viewed_at timestamptz not null default now()
);

create table if not exists public.gif_assets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  gif_id text not null,
  gif_data jsonb not null,
  created_at timestamptz not null default now(),
  unique (user_id, gif_id)
);

alter table public.favourites enable row level security;
alter table public.profiles enable row level security;
alter table public.collections enable row level security;
alter table public.collection_items enable row level security;
alter table public.gif_metadata enable row level security;
alter table public.view_history enable row level security;
alter table public.gif_assets enable row level security;

create policy "Users can manage their favourites"
on public.favourites
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can manage their profile"
on public.profiles
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can manage their collections"
on public.collections
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Public collections are readable"
on public.collections
for select
using (is_public = true or auth.uid() = user_id);

create policy "Users can manage their collection items"
on public.collection_items
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can manage their gif metadata"
on public.gif_metadata
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can manage their view history"
on public.view_history
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can manage their gif assets"
on public.gif_assets
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
